"""initial schema: data standard 1.0, cleaning template, dispatcher

Revision ID: 0001
Revises:
Create Date: 2026-09-30 11:38:19.378928
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import mia.core.db
from mia.core.events import TRIGGER_SQL

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("timestamp", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("actor_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("on_behalf_of", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approval_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prev_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_branch_id"), ["branch_id"], unique=False)

    op.create_table(
        "organisation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("default_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branch",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("organisation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_branch_organisation_id"), ["organisation_id"], unique=False
        )

    op.create_table(
        "approval",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requester_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requester_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requester_on_behalf_of", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subject_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("approver_roles", sa.JSON(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", mia.core.db.TZDateTime(length=40), nullable=True),
        sa.Column("escalate_to", sa.JSON(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decided_at", mia.core.db.TZDateTime(length=40), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_branch_id"), ["branch_id"], unique=False)

    op.create_table(
        "client",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_client_branch_id"), ["branch_id"], unique=False)

    op.create_table(
        "egress_log",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("timestamp", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("egress_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_egress_log_branch_id"), ["branch_id"], unique=False)

    op.create_table(
        "person",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("engagement_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_person_branch_id"), ["branch_id"], unique=False)

    op.create_table(
        "usage_cloud_requests",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("organisation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subagent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("task", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_cloud_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_cloud_requests_branch_id"), ["branch_id"], unique=False
        )

    op.create_table(
        "chat_threads",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_threads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_threads_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_threads_person_id"), ["person_id"], unique=False)

    op.create_table(
        "cleaning_availability",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("end", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cleaning_availability", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cleaning_availability_branch_id"), ["branch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cleaning_availability_person_id"), ["person_id"], unique=False
        )

    op.create_table(
        "cleaning_work_limits",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_daily_minutes", sa.Integer(), nullable=False),
        sa.Column("max_weekly_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cleaning_work_limits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cleaning_work_limits_branch_id"), ["branch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cleaning_work_limits_person_id"), ["person_id"], unique=True
        )

    op.create_table(
        "dispatcher_absences",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("person_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("partial_day", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reported_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dispatcher_absences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dispatcher_absences_branch_id"), ["branch_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dispatcher_absences_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dispatcher_absences_person_id"), ["person_id"], unique=False
        )

    op.create_table(
        "location",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("geofence", sa.JSON(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("access_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_location_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_location_client_id"), ["client_id"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("blocks", sa.JSON(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_messages", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chat_threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_messages_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "cleaning_sites",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("location_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("floor_area_m2", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cleaning_sites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cleaning_sites_branch_id"), ["branch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cleaning_sites_location_id"), ["location_id"], unique=False
        )

    op.create_table(
        "job",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("location_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recurrence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("required_skills", sa.JSON(), nullable=False),
        sa.Column("resources", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_location_id"), ["location_id"], unique=False)

    op.create_table(
        "cleaning_checklists",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cleaning_checklists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cleaning_checklists_branch_id"), ["branch_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cleaning_checklists_job_id"), ["job_id"], unique=False)

    op.create_table(
        "visit",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("updated_at", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("assigned_person_ids", sa.JSON(), nullable=False),
        sa.Column("planned_start", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("planned_end", mia.core.db.TZDateTime(length=40), nullable=False),
        sa.Column("actual_start", mia.core.db.TZDateTime(length=40), nullable=True),
        sa.Column("actual_end", mia.core.db.TZDateTime(length=40), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proof_refs", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_visit_branch_id"), ["branch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_visit_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_visit_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_visit_location_id"), ["location_id"], unique=False)

    # ### end Alembic commands ###
    # The events table is append-only: abort any UPDATE or DELETE.
    for statement in TRIGGER_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS events_no_update")
    op.execute("DROP TRIGGER IF EXISTS events_no_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_visit_location_id"))
        batch_op.drop_index(batch_op.f("ix_visit_job_id"))
        batch_op.drop_index(batch_op.f("ix_visit_date"))
        batch_op.drop_index(batch_op.f("ix_visit_branch_id"))

    op.drop_table("visit")
    with op.batch_alter_table("cleaning_checklists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cleaning_checklists_job_id"))
        batch_op.drop_index(batch_op.f("ix_cleaning_checklists_branch_id"))

    op.drop_table("cleaning_checklists")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_location_id"))
        batch_op.drop_index(batch_op.f("ix_job_branch_id"))

    op.drop_table("job")
    with op.batch_alter_table("cleaning_sites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cleaning_sites_location_id"))
        batch_op.drop_index(batch_op.f("ix_cleaning_sites_branch_id"))

    op.drop_table("cleaning_sites")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_thread_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_branch_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_client_id"))
        batch_op.drop_index(batch_op.f("ix_location_branch_id"))

    op.drop_table("location")
    with op.batch_alter_table("dispatcher_absences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dispatcher_absences_person_id"))
        batch_op.drop_index(batch_op.f("ix_dispatcher_absences_date"))
        batch_op.drop_index(batch_op.f("ix_dispatcher_absences_branch_id"))

    op.drop_table("dispatcher_absences")
    with op.batch_alter_table("cleaning_work_limits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cleaning_work_limits_person_id"))
        batch_op.drop_index(batch_op.f("ix_cleaning_work_limits_branch_id"))

    op.drop_table("cleaning_work_limits")
    with op.batch_alter_table("cleaning_availability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cleaning_availability_person_id"))
        batch_op.drop_index(batch_op.f("ix_cleaning_availability_branch_id"))

    op.drop_table("cleaning_availability")
    with op.batch_alter_table("chat_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_threads_person_id"))
        batch_op.drop_index(batch_op.f("ix_chat_threads_branch_id"))

    op.drop_table("chat_threads")
    with op.batch_alter_table("usage_cloud_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_cloud_requests_branch_id"))

    op.drop_table("usage_cloud_requests")
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_person_branch_id"))

    op.drop_table("person")
    with op.batch_alter_table("egress_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_egress_log_branch_id"))

    op.drop_table("egress_log")
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_branch_id"))

    op.drop_table("client")
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_branch_id"))

    op.drop_table("approval")
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_branch_organisation_id"))

    op.drop_table("branch")
    op.drop_table("organisation")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_branch_id"))
        batch_op.drop_index(batch_op.f("ix_events_action"))

    op.drop_table("events")
    # ### end Alembic commands ###
